name: pr-release

on:
  push:
    branches: [ $target ]

jobs:
  merge:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    # todo-james replace with npx pr-release pr
    - run: node lib/index.js merge --verbose --target $target --source $source
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Uncomment to publish to npm
    # - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
    #   name: Setup NPM Auth
    #   env:
    #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    # - run: npm publish
    #   name: Publish
