name: pr

on:
  push:
    branches: [ $source ]

  workflow_dispatch:

jobs:
  pr:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    # todo-james replace with npx pr-release pr
    - run: npx pr-release pr --verbose --target $target --source $source --compact
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    # The following publishes a pre-release version every time `$source` is updated
    - run: npm version --no-verify --no-commit-hooks --no-git-tag-version $(npx pr-release infer-version)  # prr:comment
    - run: npm version --no-verify --no-commit-hooks --no-git-tag-version prerelease --preid=$source       # prr:comment
    - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc                                # prr:comment
      name: Setup NPM Auth                                                                              # prr:comment
      env:                                                                                              # prr:comment
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}                                                             # prr:comment
    - run: npm publish --tag=$source                                                                       # prr:comment