name: rollback

on:
  workflow_dispatch:

jobs:
  pr:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
      with: 
        ref: '$source'
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    # todo-james replace with npx pr-release rollback
    - run: npx pr-release rollback --verbose --target $target --source $source --verbose --ignore 'package*' --ignore changelog.md
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}