name: feature

on:
  push:
  workflow_dispatch:

concurrency: prr:feature-${{ github.ref }}

jobs:
  feature:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: node bin.js feature-pr --verbose --target main --source next
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}