name: merge

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  merge:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: node bin.js changelog --target main --source next --out changelog.md --verbose
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    - run: ls
    - run: git diff
    - run: node bin.js merge --target main --source next --commit --verbose --refresh-clean
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      name: Setup NPM Auth
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - run: npm publish
      name: Publish
