name: pr

on:
  push:
    branches: [ next ]

  workflow_dispatch:

jobs:
  pr:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    # todo-james replace with npx pr-release pr
    - run: node bin.js pr --verbose --target main --source next --compact
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

    # The following publishes a pre-release version every time `next` is updated
    - run: npm version --no-verify --no-commit-hooks --no-git-tag-version $(node bin.js infer-version)  # prr:comment
    - run: npm version --no-verify --no-commit-hooks --no-git-tag-version prerelease --preid=next       # prr:comment
    - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc                                # prr:comment
      name: Setup NPM Auth                                                                              # prr:comment
      env:                                                                                              # prr:comment
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}                                                             # prr:comment
    - run: npm publish --tag=next                                                                       # prr:comment